version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: concert_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: concert_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - concert_network

  redis:
    image: redis:latest
    container_name: concert_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - concert_network

  app:
    build: .
    container_name: concert
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/concert_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: concert_redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - concert_network

volumes:
  postgres_data:

networks:
  concert_network:
    driver: bridge